name: godocmd
on: [push]
jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Install GoDocMD
        run: |
          go install github.com/tjgurwara99/godocmd@v0.1.3
      - name: Configure Github Action
        run: |
          git config --global user.name github-action
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
      - name: Update README.md file
        run: |
          godocmd -r -module ./ -w
      - name: Commit changes if README.md is different
        run: |
          if [[ `git status --porcelain` ]]; then
            git commit -am "Updated Documentation in README.md"
            git push
          else
            echo "NO CHANGES DETECTED"
          fi
