# https://github.com/golangci/golangci-lint
name: golangci-lint
on: [push, pull_request]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.31
          args: --issues-exit-code=0  # Hopefully someday we can remove this...
          working-directory: sorts    # Hopefully someday we can remove this... 
          only-new-issues: true  # Let's focus on this PR first
      - run: go version ; golangci-lint --version  # Fix the following and remove || true
      - run: golangci-lint run --no-config ciphers                            || true
      - run: golangci-lint run --no-config data-structures/binary-tree        || true
      - run: golangci-lint run --no-config data-structures/dynamic-array      || true
      - run: golangci-lint run --no-config data-structures/hash-map           || true
      - run: golangci-lint run --no-config data-structures/linked-list        || true
      - run: golangci-lint run --no-config data-structures/trie               || true
      - run: golangci-lint run --no-config dynamic-programming                || true
      - run: golangci-lint run --no-config other                              || true
      - run: golangci-lint run --no-config searches                           || true
      - run: golangci-lint run --no-config sorts
      # - run: golangci-lint run --no-config strings/...
      - run: golangci-lint run --no-config "strings/multiple string matching" || true
      # - run: golangci-lint run --no-config "strings/single string matching"   || true
      - run: golangci-lint run --no-config strings/levenshteindistance
      - run: golangci-lint run --no-config strings/naivesearch
      - run: golangci-lint run --no-config math/gcd
      - run: golangci-lint run --no-config math/power
      - run: golangci-lint run --no-config math/primecheck
      - run: golangci-lint run --no-config math/sieve                         || true
