# https://github.com/golangci/golangci-lint
name: golangci-lint
on: [push, pull_request]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.27
          args: --issues-exit-code=0  #Â Someday we can remove this...
      - run: |
          go version ; golangci-lint --version
          golangci-lint run --no-config                        || true    
      - run: golangci-lint run --no-config ciphers strings
      - run: golangci-lint run --no-config data-structures     || true
      - run: golangci-lint run --no-config dynamic-programming || true
      - run: golangci-lint run --no-config other               || true
      - run: golangci-lint run --no-config searches            || true
      - run: golangci-lint run --no-config sorts
