# https://github.com/golangci/golangci-lint
name: golang_lint_and_test
on: [push, pull_request]
jobs:
  golang_lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go version
      - uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be
          # specified without patch version: we always use the latest patch version.
          # https://github.com/golangci/golangci-lint/releases
          version: v1.39
      - run: go test $(go list ./... | grep -v /sbom | grep -v /rsa_cipher)