# https://github.com/golangci/golangci-lint
name: golangci-lint
on: [push, pull_request]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.27
          working-directory: sorts
          args: --issues-exit-code=0  # Hopefully someday we can remove this...
          # Only show new issues if this is a pull request...
          # only-new-issues: true
      - run: echo "::set-env name=PATH::/home/runner/golangci-lint-1.27.0-linux-amd64:$PATH"
      - run: go version ; golangci-lint --version  # Fix the following and remove || true
      - run: golangci-lint run --no-config ciphers                            || true
      - run: golangci-lint run --no-config data-structures/binary-tree        || true
      - run: golangci-lint run --no-config data-structures/dynamic-array      || true
      - run: golangci-lint run --no-config data-structures/hash-map           || true
      - run: golangci-lint run --no-config data-structures/linked-list        || true
      - run: golangci-lint run --no-config data-structures/trie               || true
      - run: golangci-lint run --no-config dynamic-programming                || true
      - run: golangci-lint run --no-config other                              || true
      - run: golangci-lint run --no-config searches                           || true
      - run: golangci-lint run --no-config sorts
      - run: golangci-lint run --no-config strings                            || true
      - run: golangci-lint run --no-config "strings/multiple-string-matching" || true
      # - run: golangci-lint run --no-config "strings/single string matching"   || true
