# https://github.com/golangci/golangci-lint
name: golangci-lint
on: [push, pull_request]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v1
    - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.21.0
    - run: |
        go version ; ./bin/golangci-lint --version
        ./bin/golangci-lint run --no-config                        || true    
    - run: ./bin/golangci-lint run --no-config ciphers strings
    - run: ./bin/golangci-lint run --no-config data-structures     || true
    - run: ./bin/golangci-lint run --no-config dynamic-programming || true
    - run: ./bin/golangci-lint run --no-config other               || true
    - run: ./bin/golangci-lint run --no-config searches            || true
    - run: ./bin/golangci-lint run --no-config sorts
