# https://github.com/golangci/golangci-lint
name: golang_lint_and_test
on: [push, pull_request]
jobs:
  golang_lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: codespell-project/actions-codespell@master
        with:
          skip: "go.mod,go.sum"
          ignore_words_list: "actualy,nwe"
      - run: go version
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: -E gofmt
      - run: go test ./...
