# https://github.com/golangci/golangci-lint
name: golangci-lint
on: [push, pull_request]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.31
          args: --issues-exit-code=0  # Hopefully someday we can remove this...
          working-directory: sorts    # Hopefully someday we can remove this... and enable only-new-issues
          # only-new-issues: true  # Let's focus on this PR first
      - run: echo "/home/runner/golangci-lint-1.31.0-linux-amd64" >> $GITHUB_PATH
      - run: go version ; golangci-lint --version  # Fix the following and remove || true
      - run: golangci-lint run --no-config ciphers/...
      # - run: golangci-lint run --no-config datastructures/binary-tree        || true
      # - run: golangci-lint run --no-config datastructures/dynamic-array      || true
      # - run: golangci-lint run --no-config datastructures/hashmap
      # - run: golangci-lint run --no-config datastructures/linkedlist        || true
      # - run: golangci-lint run --no-config datastructures/trie               || true
      - run: golangci-lint run --no-config dynamicprogramming/...
      - run: golangci-lint run --no-config other/...
      - run: golangci-lint run --no-config searches/...
      - run: golangci-lint run --no-config sorts/...
      - run: golangci-lint run --no-config strings/...
      # - run: golangci-lint run --no-config "strings/multiple-string-matching" || true
      # - run: golangci-lint run --no-config "strings/single string matching"   || true
      # - run: golangci-lint run --no-config strings/levenshteindistance
      # - run: golangci-lint run --no-config strings/naivesearch
      - run: golangci-lint run --no-config math/...
      # - run: golangci-lint run --no-config math/gcd
      # - run: golangci-lint run --no-config math/power
      # - run: golangci-lint run --no-config math/primecheck
      # - run: golangci-lint run --no-config math/sieve                         || true
